version: 0.2

env:

  parameter-store:
    DOCKERHUB_USER: "/docker/username"
  secrets-manager:
    DOCKERHUB_TOKEN: "docler_creds:token"

phases:

  pre_build:
    commands:
      - echo ${DOCKERHUB_TOKEN} | docker login -u ${DOCKERHUB_USER} --password-stdin
  build:
    commands:
      - docker build -t angular-ecs-build:latest .

  post_build:
    commands:
      - docker tag angular-ecs-build:latest ${DOCKERHUB_USER}/angular-ecs-build:latest
      - docker push ${DOCKERHUB_USER}/angular-ecs-build:latest
